theme: jekyll-theme-minimal
logo: https://media-exp2.licdn.com/dms/image/C4E03AQGDF88bmRiimA/profile-displayphoto-shrink_800_800/0/1655191599397?e=1662595200&v=beta&t=qcma0EMFXHS8Q-gA0UOPKSOMX21uThGeaI6EnfWzaQw
title: Anton Plavinsky's cv
description: Anton Plavinsky's cv on GitHub Pages.
show_downloads: false
google_analytics: 3822356097
